-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
        -   id: trailing-whitespace
        -   id: autopep8-wrapper
            args:
            - --max-line-length=130
            - -a
            - -i
            - --ignore=E265,E309,E501
            - -v
        -   id: check-json
        -   id: check-yaml
        -   id: debug-statements
        -   id: check-merge-conflict
        -   id: check-added-large-files
        -   id: flake8
            args: [--max-line-length=131]
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b7f5d468c67c3c4a6ea7cdf68c40778095b0f19b
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: 'master'
    hooks:
    -   id: pep257
