-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
        -   id: trailing-whitespace
        -   id: flake8
            args: [--max-line-length=131]
        -   id: autopep8-wrapper
            args:
            - -i
            - --ignore=E265,E309,E501
            - -v
        -   id: check-json
        -   id: check-yaml
        -   id: check-ast
        -   id: end-of-line-fixer
        -   id: debug-statements
        -   id: check-merge-conflicts
        -   id: whitespace
        -   id: check-added-large-file
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b7f5d468c67c3c4a6ea7cdf68c40778095b0f19b
    hooks:
    -   id: pep257
    -   id: python-import-sorter
        args:
        - --silent-overwrite
